apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesensei
  labels:
    app: kubesensei
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubesensei
  template:
    metadata:
      labels:
        app: kubesensei
    spec:
      containers:
        - name: kubesensei
          image: willchrist/kubesensei:1.5
          imagePullPolicy: Always
          env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: tc-analyzer-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: tc-analyzer-secret
                  key: AWS_SECRET_ACCESS_KEY
         
